---

- name: Install avahi-daemon package
  apt: pkg=avahi-daemon state=present

- name: Install avahi-utils package
  when: avahi_install_utils
  apt: pkg=avahi-daemon state=present

- name: Avahi | Update avahi config
  template:
    src: avahi-daemon.conf.j2
    dest: "/etc/avahi/avahi-daemon.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart avahi-daemon

